//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domein
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Author
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Author()
        {
            this.Books = new HashSet<Book>();
        }
    
        public int AuthorID { get; set; }

        [Required]
        [StringLength(60, MinimumLength = 3)]
        public string AuthorName { get; set; }
        
        [Required]
        [StringLength(60, MinimumLength = 3)]
        public string AuthorLastName { get; set; }

        public Nullable<System.DateTime> BirthDay { get; set; }
        public byte[] Picture { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Book> Books { get; set; }
    }
    public partial class Author
    {
        private string fullName;
        public string FullName
        {
            get
            {
                fullName = AuthorName + " " + AuthorLastName;
                return fullName;
            }
        }
    }
}
