//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domein
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookAddAttribute
    {
        public int BookAddAttributesID { get; set; }
        public int BookID { get; set; }
        public int AttributeID { get; set; }
        public string ValueTypeText { get; set; }
        public Nullable<System.DateTime> ValueTypeDate { get; set; }
        public Nullable<bool> Ganre { get; set; }
        public Nullable<int> GanreID { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual ExtraAttribute ExtraAttribute { get; set; }
        public virtual Ganre Ganre1 { get; set; }
    }
}
